In [6]:
import numpy as np

In [18]:
x = np.array([3,1,2,3,3])
max_index = np.argwhere(x == x.max())
print(max_index)
print(max_index[1,0])

[[0]
 [3]
 [4]]
3


In [25]:
import re

l = 'F:\\ZS_Aorta\\20201030\\ZS16093253_ZS0023607916_1\\WholeBody CTA\\CTA 1.0 CE'
l = re.search(r"202\d{5}\\ZS[0-9ZS_]*\\Wh", l).group()[0:-3]
l = l.replace("\\", "_")
print(l)

20201030_ZS16093253_ZS0023607916_1


In [36]:
arr = np.array([1,2,3])

In [37]:
print(np.where(arr == 3))

(array([2], dtype=int64),)


In [39]:
arr[np.where(arr == 3)] = 1

In [40]:
arr

array([1, 2, 1])

In [45]:
FOLDER_DICT = {"seg": "Segmented axial", 
               "AAO": "AAO",
               "BCT": "BCT",
               "DAO": "DAO",
               "LCCA": "LCCA",
               "LSA": "LSA"}
for i in FOLDER_DICT:
    print(FOLDER_DICT[i])

Segmented axial
AAO
BCT
DAO
LCCA
LSA
